# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

dropbox_app_key: "qlarl34d6gl04py"
dropbox_app_secret: "3b8qtu51vmq3808"
dropbox_access_token: "cd3zyw7w9u1kz2sf"
dropbox_access_token_secret: "y8bkpunxu10l8sv"
dropbox_user_id: "221916271"
dropbox_access_type: "app_folder"
MANDRILL_API_KEY: 3mCP_bV9dECo_SLAl8SaFQ

production:
  dropbox_app_key: "qlarl34d6gl04py"
  dropbox_app_secret: "3b8qtu51vmq3808"
  dropbox_access_token: "cd3zyw7w9u1kz2sf"
  dropbox_access_token_secret: "y8bkpunxu10l8sv"
  dropbox_user_id: "221916271"
  dropbox_access_type: "app_folder"
  MANDRILL_API_KEY: 3mCP_bV9dECo_SLAl8SaFQ
  